#include <QApplication>
#include <QIcon>

#include "../globals.h"
#include "mainwindow.h"
#ifdef Q_OS_MAC
#include "../libs/cocoainitializer/cocoainitializer.h"
#endif
#include <QDebug>
#include "version.h" // Autogenerated version file via build


const int BLAH = 1;

int main(int argc, char *argv[])
{
    qDebug() << Snowberry::SnowGUI::SNOWGUI_RELEASE_VERSION << "release";
    QApplication a(argc, argv);
#ifdef Q_OS_MAC
    CocoaInitializer initializer;
    Q_UNUSED(initializer)
#else
    a.setWindowIcon(QIcon(":/icons/qjsonify-64x64.png"));
#endif
    a.setApplicationName(QObject::tr(Snowberry::Strings::PROGRAM_NAME_SNOWBERRY.toLatin1()));
    a.setApplicationVersion("%");
    MainWindow w;
    w.show();

    return a.exec();
}
